### DISCUSSION TITLE
Add output variables to docker action

### DISCUSSION THREAD

**Discussion by JeroenKnoops** [philips-software/docker-ci-scripts#45] [Ideas]
# Problem
In the config you can configure docker registries and the naming of the docker images.
We want to use those names to perform additional actions on the created images like testing the image or scanning with `tern`

# Solution
Ouput the following fields:
- `image-name` --> Pass image-name also as ouptut. f.e. `node`
- `base-image` --> This is the first in the list with tags. f.e. `https://docker.io/philipssoftware/node:10`
- `all-images` --> `['https://docker.io/philipssoftware/node:10', 'https://docker.io/philipssoftware/node:10.0']`

# Usage
```
- uses: philips-software/docker-ci-scripts@v3.0.0
  id: node
  with:
    dockerfile: './docker/Dockerfile'
    image-name: 'node'
    tags: 'latest 12 12.1 12.1.4'
  env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
    DOCKER_ORGANIZATION: myDockerOrganization
- uses: philips-labs/tern-action@v1.1.0
  id: scan
  with:
    image: ${{ steps.node.outputs.base-image }}
    format: yaml
    output: ${{ steps.node.outputs.image-name }}.yaml
- uses: actions/upload-artifact@v2
  with:
    name: tern 
    path: ${{ steps.scan.outputs.file }} 
```

# Related issues
Related to #42
42 is about showing it in the output log. This ticket is about exposing it in variables so other jobs can use it.
