### ISSUE TITLE
Projects with base-dir cannot be signed.

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/docker-ci-scripts#99]
When trying to sign an image with a base-dir (like submodule), signing the image goes wrong.

# Example workflow
```yaml
  manual_build:
    name: tern manual
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Build Docker Images with Tern and scancode latest
        uses: philips-software/docker-ci-scripts@v4.0.0
        with:
          dockerfile: docker/Dockerfile.scancode
          image-name: tern
          tags: latest-scancode
          base-dir: latest/tern
          slsa-provenance: true
          sign: true
```

# Example build-pipeline
https://github.com/philips-software/docker-tern/runs/4963399210?check_suite_focus=true

# Error message
```
Signing image
Sign image
Pushing signature to: index.docker.io/***/tern
Verify signing
Error: loading public key: open cosign.pub: no such file or directory
main.go:46: error during command execution: loading public key: open cosign.pub: no such file or directory
```
